type = "checkout_ui_extension"
name = "blustream-checkout-extension"


extension_points = [
  'Checkout::Actions::RenderBefore'
]

[[metafields]]
namespace = "blustream"
key = "ConsentAccepted"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/settings
# [[settings.fields]]
# key = "heading"
# name = "Heading"
# type = "single_line_text_field"
